Student.create(name:"Karla")
Student.create(name:"Benni")
Student.create(name:"Sean")
Student.create(name:"Regina")

Badge.create(text: "Biggest goofball", student_id: 1)
Badge.create(text: "Loves pizza", student_id: 2)
Badge.create(text: "Most likely to eat a cookie", student_id: 3)
Badge.create(text: "Best smile", student_id: 4)
Badge.create(text: "Loves Rspec", student_id: 1)
Badge.create(text: "Best coder", student_id: 2)
Badge.create(text: "Silly sally", student_id: 3)
Badge.create(text: "Best hair", student_id: 4)
