Student.delete_all
Badge.delete_all

Student.create(first_name: "Hanah", last_name: "Yendler")
Student.create(first_name: "Karla", last_name: "King")
Student.create(first_name: "Shawn", last_name: "Spears")
Student.create(first_name: "Regina", last_name: "Wong")
Student.create(first_name: "Natasha", last_name: "Thapayali")
Student.create(first_name: "Jon", last_name: "Huang")
Student.create(first_name: "Michael", last_name: "Du")
Student.create(first_name: "Walter", last_name: "Kerr")
Student.create(first_name: "Ryan", last_name: "Ho")
Student.create(first_name: "Josh", last_name: "Smith")
Student.create(first_name: "Beni", last_name: "Shpringer")
Student.create(first_name: "Lindsey", last_name: "Stevenson")
Student.create(first_name: "Bernice", last_name: "Chua")
Student.create(first_name: "Fatma", last_name: "Ocal")
Student.create(first_name: "Cole", last_name: "")
Student.create(first_name: "Michael W", last_name: "Whelpley")
Student.create(first_name: "Sean", last_name: "Massih")
Student.create(first_name: "Ovi", last_name: "Smith")
Student.create(first_name: "Lu", last_name: "De Castro")

Badge.create(text: "test", student_id: 1)
Badge.create(text: "test", student_id: 2)
Badge.create(text: "test", student_id: 3)
Badge.create(text: "test", student_id: 4)
Badge.create(text: "test", student_id: 5)
Badge.create(text: "test", student_id: 6)
Badge.create(text: "test", student_id: 7)
Badge.create(text: "test", student_id: 8)
Badge.create(text: "test", student_id: 9)
Badge.create(text: "test", student_id: 10)
Badge.create(text: "test", student_id: 11)
Badge.create(text: "test", student_id: 12)
Badge.create(text: "test", student_id: 13)
Badge.create(text: "test", student_id: 14)
Badge.create(text: "test", student_id: 15)
Badge.create(text: "test", student_id: 16)
Badge.create(text: "test", student_id: 17)
Badge.create(text: "test", student_id: 18)
Badge.create(text: "test", student_id: 19)